<!-- SPDX-License-Identifier: MPL-2.0 -->

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>RelayBridge.Setup</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppHostDotNetSearch>Global</AppHostDotNetSearch>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RelayBridge.Core\RelayBridge.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>RelayBridge.IntegrationTests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>RelayBridge.ConsoleHostProbe</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
