// SPDX-License-Identifier: MPL-2.0

using System.Text;
using System.Text.Json;
using RelayBridge.Core.Microsoft;

namespace RelayBridge.Infrastructure.Microsoft;

public sealed class MicrosoftSetupScriptGenerator
{
    private const string ApplicationDisplayNamePrefix = "RelayBridge SMTP OAuth";
    private const string GroupNamePrefix = "RelayBridge Allowed Senders";
    private const string ScopeNamePrefix = "RelayBridge Allowed Senders Scope";
    private const string AssignmentNamePrefix = "RelayBridge SMTP SendAs";

    public string GenerateEntraScript(
        MicrosoftSetupState state,
        string publicCertificatePath,
        DateTimeOffset generatedAt)
    {
        ArgumentNullException.ThrowIfNull(state);
        ArgumentException.ThrowIfNullOrWhiteSpace(publicCertificatePath);
        if (state.Certificate is null)
        {
            throw new InvalidOperationException("Choose a certificate before generating the Microsoft application script.");
        }

        if (publicCertificatePath.IndexOfAny(['\r', '\n', '\0']) >= 0)
        {
            throw new ArgumentException("The public certificate path contains unsupported characters.", nameof(publicCertificatePath));
        }

        if (state.Mode == MicrosoftSetupMode.ExistingApplication &&
            (state.TenantId is null || state.ClientId is null))
        {
            throw new InvalidOperationException("Enter the existing tenant and application IDs first.");
        }

        var applicationDisplayName = $"{ApplicationDisplayNamePrefix} {state.Certificate.Thumbprint[^12..]}";
        var payload = EncodePayload(new EntraScriptPayload(
            state.Mode.ToString(),
            publicCertificatePath,
            applicationDisplayName,
            state.TenantId?.ToString("D"),
            state.ClientId?.ToString("D")));

        return $$"""
            # Generated by RelayBridge
            # Purpose: Configure the Microsoft Entra application and public certificate
            # Generated: {{generatedAt.ToUniversalTime():O}}
            # Run in PowerShell 7. This script never handles the certificate private key.
            # Run the Exchange stage later in a separate, fresh PowerShell 7 process.

            Set-StrictMode -Version Latest
            $ErrorActionPreference = 'Stop'
            $setup = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('{{payload}}')) | ConvertFrom-Json

            if (-not (Get-Module -ListAvailable -Name Microsoft.Graph.Authentication)) {
                throw 'Microsoft.Graph PowerShell is required. Install it for your user, then rerun this script: Install-Module Microsoft.Graph -Scope CurrentUser'
            }

            Import-Module Microsoft.Graph.Authentication -ErrorAction Stop
            Import-Module Microsoft.Graph.Applications -ErrorAction Stop
            Connect-MgGraph -Scopes 'Application.ReadWrite.All' -NoWelcome

            try {
                $context = Get-MgContext
                if (-not $context -or -not $context.TenantId) {
                    throw 'Microsoft Entra sign-in did not return a tenant identifier.'
                }

                if ($setup.TenantId -and ([Guid]$setup.TenantId -ne [Guid]$context.TenantId)) {
                    throw 'The signed-in tenant does not match the tenant entered in RelayBridge. No changes were made.'
                }

                $certificate = [Security.Cryptography.X509Certificates.X509Certificate2]::new([string]$setup.CertificatePath)
                if ($certificate.HasPrivateKey) {
                    throw 'The selected file unexpectedly contains a private key. Use the RelayBridge public .cer export.'
                }

                if ($setup.Mode -eq 'NewApplication') {
                    $matches = @(Get-MgApplication -Filter "displayName eq '$($setup.ApplicationDisplayName)'" -All -Property Id,AppId,DisplayName,SignInAudience,RequiredResourceAccess,KeyCredentials)
                    if ($matches.Count -gt 1) {
                        throw 'More than one Entra application has the RelayBridge name. Resolve the conflict before continuing.'
                    }

                    if ($matches.Count -eq 0) {
                        $application = New-MgApplication -BodyParameter @{
                            displayName = [string]$setup.ApplicationDisplayName
                            signInAudience = 'AzureADMyOrg'
                            requiredResourceAccess = @()
                            keyCredentials = @(@{
                                type = 'AsymmetricX509Cert'
                                usage = 'Verify'
                                key = $certificate.RawData
                                displayName = 'RelayBridge Authentication'
                                startDateTime = $certificate.NotBefore.ToUniversalTime()
                                endDateTime = $certificate.NotAfter.ToUniversalTime()
                            })
                        }
                    }
                    else {
                        $application = $matches[0]
                        $thumbprintMatches = @($application.KeyCredentials | Where-Object {
                            $_.CustomKeyIdentifier -and
                            ([Convert]::ToHexString([byte[]]$_.CustomKeyIdentifier) -eq $certificate.Thumbprint)
                        })
                        if ($thumbprintMatches.Count -ne 1) {
                            throw 'A RelayBridge-named application already exists with different certificate credentials. Use the existing-application path or resolve the conflict. No changes were made.'
                        }
                    }
                }
                else {
                    $matches = @(Get-MgApplication -Filter "appId eq '$($setup.ClientId)'" -All -Property Id,AppId,DisplayName,SignInAudience,RequiredResourceAccess,KeyCredentials)
                    if ($matches.Count -ne 1) {
                        throw 'The existing Application ID did not resolve to exactly one application in this tenant.'
                    }

                    $application = Get-MgApplication -ApplicationId $matches[0].Id -Property Id,AppId,DisplayName,SignInAudience,RequiredResourceAccess,KeyCredentials
                }

                if ($application.SignInAudience -ne 'AzureADMyOrg') {
                    throw 'RelayBridge requires a single-tenant Microsoft application. No changes were made.'
                }

                $configuredPermissions = @($application.RequiredResourceAccess | ForEach-Object { @($_.ResourceAccess) }).Count
                if ($configuredPermissions -ne 0) {
                    throw 'The application contains API permission entries. RelayBridge App RBAC requires zero Entra mailbox API permissions. No changes were made.'
                }

                $servicePrincipals = @(Get-MgServicePrincipal -Filter "appId eq '$($application.AppId)'" -All -Property Id,AppId,DisplayName)
                if ($servicePrincipals.Count -gt 1) {
                    throw 'More than one service principal references this application. Resolve the conflict before continuing.'
                }

                if ($servicePrincipals.Count -eq 0) {
                    $servicePrincipal = New-MgServicePrincipal -BodyParameter @{ appId = [string]$application.AppId }
                }
                else {
                    $servicePrincipal = $servicePrincipals[0]
                }

                $assignedPermissions = @(Get-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $servicePrincipal.Id -All -ErrorAction Stop).Count
                if ($assignedPermissions -ne 0) {
                    throw 'The service principal has API permission assignments. Remove them before continuing with scoped Exchange App RBAC. No certificate changes were made.'
                }

                if ($setup.Mode -eq 'ExistingApplication') {
                    $thumbprintMatches = @($application.KeyCredentials | Where-Object {
                        $_.CustomKeyIdentifier -and
                        ([Convert]::ToHexString([byte[]]$_.CustomKeyIdentifier) -eq $certificate.Thumbprint)
                    })
                    if ($thumbprintMatches.Count -eq 0) {
                        $keys = @($application.KeyCredentials)
                        $keys += @{
                            type = 'AsymmetricX509Cert'
                            usage = 'Verify'
                            key = $certificate.RawData
                            displayName = 'RelayBridge Authentication'
                            startDateTime = $certificate.NotBefore.ToUniversalTime()
                            endDateTime = $certificate.NotAfter.ToUniversalTime()
                        }
                        Update-MgApplication -ApplicationId $application.Id -BodyParameter @{ keyCredentials = $keys }
                        $application = Get-MgApplication -ApplicationId $application.Id -Property Id,AppId,RequiredResourceAccess,KeyCredentials,SignInAudience
                    }
                }

                $configuredPermissions = @($application.RequiredResourceAccess | ForEach-Object { @($_.ResourceAccess) }).Count
                $permissionCount = $configuredPermissions + $assignedPermissions
                if ($permissionCount -ne 0) {
                    throw 'The application or service principal has API permission assignments. Remove them before continuing with scoped Exchange App RBAC.'
                }

                [ordered]@{
                    TenantId = [Guid]$context.TenantId
                    ClientId = [Guid]$application.AppId
                    ServicePrincipalObjectId = [Guid]$servicePrincipal.Id
                    ApiPermissionEntryCount = 0
                } | ConvertTo-Json -Compress
            }
            finally {
                Disconnect-MgGraph -ErrorAction SilentlyContinue | Out-Null
            }
            """;
    }

    public string GenerateExchangeScript(MicrosoftSetupState state, DateTimeOffset generatedAt)
    {
        ArgumentNullException.ThrowIfNull(state);
        if (state.ClientId is null || state.ServicePrincipalObjectId is null ||
            string.IsNullOrWhiteSpace(state.SenderMailbox))
        {
            throw new InvalidOperationException("Microsoft application identifiers and a sender mailbox are required.");
        }

        MicrosoftSetupValidation.ValidateMailbox(state.SenderMailbox);
        var objectSuffix = state.ClientId.Value.ToString("N")[..8];
        var payload = EncodePayload(new ExchangeScriptPayload(
            state.ClientId.Value.ToString("D"),
            state.ServicePrincipalObjectId.Value.ToString("D"),
            state.SenderMailbox,
            $"{GroupNamePrefix} {objectSuffix}",
            $"RelayBridgeSenders{objectSuffix}",
            $"{ScopeNamePrefix} {objectSuffix}",
            $"{AssignmentNamePrefix} {objectSuffix}"));

        return $$"""
            # Generated by RelayBridge
            # Purpose: Restrict Exchange SMTP SendAs permission to the selected sender mailbox
            # Generated: {{generatedAt.ToUniversalTime():O}}
            # Run in a new PowerShell 7 process after closing the Entra setup process.

            Set-StrictMode -Version Latest
            $ErrorActionPreference = 'Stop'
            $setup = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('{{payload}}')) | ConvertFrom-Json
            $roleName = 'Application SMTP.SendAsApp'

            if (-not (Get-Module -ListAvailable -Name ExchangeOnlineManagement)) {
                throw 'ExchangeOnlineManagement is required. Install it for your user, then rerun this script: Install-Module ExchangeOnlineManagement -Scope CurrentUser'
            }

            Import-Module ExchangeOnlineManagement -ErrorAction Stop
            Connect-ExchangeOnline -ShowBanner:$false

            try {
                $sender = Get-Recipient -Identity ([string]$setup.SenderMailbox) -ErrorAction Stop
                if (-not $sender.PrimarySmtpAddress) {
                    throw 'The selected sender is not an Exchange recipient with a primary SMTP address. No changes were made.'
                }

                $exchangeServicePrincipals = @(Get-ServicePrincipal | Where-Object { [string]$_.AppId -eq [string]$setup.ClientId })
                if ($exchangeServicePrincipals.Count -gt 1) {
                    throw 'More than one Exchange service-principal reference uses this Application ID. Resolve the conflict before continuing.'
                }
                $exchangeServicePrincipal = $null
                if ($exchangeServicePrincipals.Count -eq 1) {
                    $exchangeServicePrincipal = $exchangeServicePrincipals[0]
                    if ([Guid]$exchangeServicePrincipal.ObjectId -ne [Guid]$setup.ServicePrincipalObjectId) {
                        throw 'The existing Exchange service-principal reference points to a different Entra object. No changes were made.'
                    }
                }

                $group = Get-DistributionGroup -Identity ([string]$setup.GroupName) -ErrorAction SilentlyContinue
                $groupMarker = "RelayBridge:$($setup.ClientId)"
                if ($group -and [string]$group.CustomAttribute15 -ne $groupMarker) {
                    throw 'A group with the RelayBridge name already exists but is not owned by this application. No changes were made.'
                }
                if ($group -and -not $group.DistinguishedName) {
                    throw 'The RelayBridge sender group does not expose the Exchange distinguished name required for a safe scope.'
                }

                $scope = Get-ManagementScope -Identity ([string]$setup.ScopeName) -ErrorAction SilentlyContinue
                if ($scope -and -not $group) {
                    throw 'A RelayBridge management scope exists without the expected owned sender group. No changes were made.'
                }
                if ($scope) {
                    $scopeFilter = [string]$scope.RecipientFilter
                    if ($scopeFilter.IndexOf('MemberOfGroup', [StringComparison]::OrdinalIgnoreCase) -lt 0 -or
                        $scopeFilter.IndexOf([string]$group.DistinguishedName, [StringComparison]::OrdinalIgnoreCase) -lt 0) {
                        throw 'A management scope with the RelayBridge name exists but has a different recipient filter. No changes were made.'
                    }
                }

                $assignment = Get-ManagementRoleAssignment -Identity ([string]$setup.AssignmentName) -ErrorAction SilentlyContinue
                if ($assignment) {
                    if ([string]$assignment.Role -ne $roleName -or
                        [string]$assignment.CustomResourceScope -ne [string]$setup.ScopeName -or
                        [string]$assignment.RoleAssigneeType -ne 'ServicePrincipal') {
                        throw 'A role assignment with the RelayBridge name exists but has different security settings. No changes were made.'
                    }
                    $assignedPrincipal = Get-ServicePrincipal -Identity $assignment.RoleAssignee -ErrorAction Stop
                    if ([Guid]$assignedPrincipal.AppId -ne [Guid]$setup.ClientId) {
                        throw 'The RelayBridge role assignment references a different application. No changes were made.'
                    }
                }

                # All existing named objects have passed conflict checks. Changes begin here.
                if (-not $exchangeServicePrincipal) {
                    $exchangeServicePrincipal = New-ServicePrincipal -AppId ([Guid]$setup.ClientId) -ObjectId ([Guid]$setup.ServicePrincipalObjectId) -DisplayName 'RelayBridge SMTP OAuth'
                }
                if (-not $group) {
                    $group = New-DistributionGroup -Name ([string]$setup.GroupName) -DisplayName ([string]$setup.GroupName) -Alias ([string]$setup.GroupAlias) -Type Distribution
                    Set-DistributionGroup -Identity $group.Identity -CustomAttribute15 $groupMarker
                    $group = Get-DistributionGroup -Identity $group.Identity -ErrorAction Stop
                }

                $members = @(Get-DistributionGroupMember -Identity $group.Identity -ResultSize Unlimited)
                $senderIsMember = @($members | Where-Object {
                    [string]$_.PrimarySmtpAddress -eq [string]$sender.PrimarySmtpAddress
                }).Count -eq 1
                if (-not $senderIsMember) {
                    Add-DistributionGroupMember -Identity $group.Identity -Member $sender.Identity -BypassSecurityGroupManagerCheck
                }

                if (-not $scope) {
                    $escapedDn = ([string]$group.DistinguishedName).Replace("'", "''")
                    $expectedFilter = "MemberOfGroup -eq '$escapedDn'"
                    $scope = New-ManagementScope -Name ([string]$setup.ScopeName) -RecipientRestrictionFilter $expectedFilter
                }
                if (-not $assignment) {
                    $assignment = New-ManagementRoleAssignment -Name ([string]$setup.AssignmentName) -Role $roleName -App ([Guid]$setup.ClientId) -CustomResourceScope ([string]$setup.ScopeName)
                }

                $authorization = @(Test-ServicePrincipalAuthorization -Identity ([Guid]$setup.ClientId) -Resource ([string]$setup.SenderMailbox) | Where-Object {
                    [string]$_.RoleName -eq $roleName -and $_.InScope -eq $true
                })
                if ($authorization.Count -eq 0) {
                    throw 'Exchange did not report the selected sender inside the RelayBridge SMTP scope. Rerun after propagation or inspect the scope.'
                }

                [ordered]@{
                    ServicePrincipalConfigured = $true
                    ScopeConfigured = $true
                    Role = $roleName
                    SenderInScope = $true
                } | ConvertTo-Json -Compress
            }
            finally {
                Disconnect-ExchangeOnline -Confirm:$false -ErrorAction SilentlyContinue
            }
            """;
    }

    private static string EncodePayload<T>(T value)
    {
        return Convert.ToBase64String(JsonSerializer.SerializeToUtf8Bytes(value));
    }

    private sealed record EntraScriptPayload(
        string Mode,
        string CertificatePath,
        string ApplicationDisplayName,
        string? TenantId,
        string? ClientId);

    private sealed record ExchangeScriptPayload(
        string ClientId,
        string ServicePrincipalObjectId,
        string SenderMailbox,
        string GroupName,
        string GroupAlias,
        string ScopeName,
        string AssignmentName);
}
