// SPDX-License-Identifier: MPL-2.0

using System.Runtime.Versioning;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using RelayBridge.Core.Microsoft;
using RelayBridge.Core.Queue;
using RelayBridge.Host.Services;
using RelayBridge.Infrastructure.Microsoft;
using RelayBridge.Infrastructure.Queue;
using RelayBridge.Infrastructure.Storage;
using Xunit;

namespace RelayBridge.IntegrationTests;

[SupportedOSPlatform("windows")]
public sealed class MicrosoftSetupIntegrationTests
{
    [Fact]
    public void Generated_scripts_are_separate_least_privilege_idempotent_and_fail_closed()
    {
        var generator = new MicrosoftSetupScriptGenerator();
        var state = ReadyState();

        var entra = generator.GenerateEntraScript(
            state,
            @"C:\RelayBridge Data\relaybridge-public.cer",
            DateTimeOffset.Parse("2026-08-22T10:00:00Z"));
        var exchange = generator.GenerateExchangeScript(
            state,
            DateTimeOffset.Parse("2026-08-22T10:00:00Z"));

        Assert.Contains("Generated by RelayBridge", entra, StringComparison.Ordinal);
        Assert.Contains("Microsoft.Graph.Applications", entra, StringComparison.Ordinal);
        Assert.Contains("requiredResourceAccess = @()", entra, StringComparison.Ordinal);
        Assert.Contains("ApiPermissionEntryCount = 0", entra, StringComparison.Ordinal);
        Assert.Contains("Get-MgServicePrincipalAppRoleAssignment", entra, StringComparison.Ordinal);
        Assert.Contains("More than one", entra, StringComparison.Ordinal);
        Assert.DoesNotContain("ExchangeOnlineManagement", entra, StringComparison.Ordinal);
        Assert.DoesNotContain("Mail.Send", entra, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("Mail.ReadWrite", entra, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("SMTP.SendAsApp", entra, StringComparison.Ordinal);
        Assert.DoesNotContain("AccessToken", entra, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("PFX", entra, StringComparison.OrdinalIgnoreCase);
        Assert.True(
            entra.IndexOf("Get-MgServicePrincipalAppRoleAssignment", StringComparison.Ordinal) <
            entra.IndexOf("Update-MgApplication", StringComparison.Ordinal),
            "Existing application permissions must be checked before adding a certificate.");

        Assert.Contains("ExchangeOnlineManagement", exchange, StringComparison.Ordinal);
        Assert.Contains("Application SMTP.SendAsApp", exchange, StringComparison.Ordinal);
        Assert.Contains("CustomResourceScope", exchange, StringComparison.Ordinal);
        Assert.Contains("Test-ServicePrincipalAuthorization", exchange, StringComparison.Ordinal);
        Assert.Contains("No changes were made", exchange, StringComparison.Ordinal);
        Assert.Contains("Get-DistributionGroup", exchange, StringComparison.Ordinal);
        Assert.DoesNotContain("Microsoft.Graph", exchange, StringComparison.Ordinal);
        Assert.DoesNotContain("Set-ExecutionPolicy", exchange, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("Remove-", exchange, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("AccessToken", exchange, StringComparison.OrdinalIgnoreCase);
        Assert.True(
            exchange.IndexOf("# All existing named objects have passed conflict checks", StringComparison.Ordinal) <
            exchange.IndexOf("New-ServicePrincipal -AppId", StringComparison.Ordinal),
            "Exchange object conflicts must be checked before changes begin.");
    }

    [Theory]
    [InlineData("scanner@example.com'; Remove-Item C:\\*")]
    [InlineData("scanner@example.com`nWrite-Host hacked")]
    [InlineData("scanner@example.com\r\nBcc: victim@example.com")]
    [InlineData("扫描@example.com")]
    public void Script_inputs_reject_command_injection_and_unsupported_mailboxes(string sender)
    {
        Assert.Throws<ArgumentException>(() => MicrosoftSetupValidation.ValidateMailbox(sender));
    }

    [Fact]
    public void Script_payload_encodes_values_as_data_not_executable_source()
    {
        var generator = new MicrosoftSetupScriptGenerator();
        var state = ReadyState() with { SenderMailbox = "scanner+relay@example.com" };

        var script = generator.GenerateExchangeScript(state, DateTimeOffset.UtcNow);

        Assert.DoesNotContain("scanner+relay@example.com", script, StringComparison.Ordinal);
        Assert.Contains("FromBase64String", script, StringComparison.Ordinal);
        Assert.Contains("ConvertFrom-Json", script, StringComparison.Ordinal);
    }

    [Fact]
    public void Generated_object_names_are_stable_per_candidate_and_allow_safe_side_by_side_replacement()
    {
        var generator = new MicrosoftSetupScriptGenerator();
        var generatedAt = DateTimeOffset.Parse("2026-08-22T10:00:00Z");
        var first = ReadyState();
        var second = first with
        {
            Certificate = MicrosoftCertificateReference.Create(new string('B', 40), CertificateStoreTarget.CurrentUser),
            ClientId = Guid.Parse("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
        };

        using var firstEntra = DecodeScriptPayload(generator.GenerateEntraScript(first, @"C:\public.cer", generatedAt));
        using var stableEntra = DecodeScriptPayload(generator.GenerateEntraScript(first, @"C:\public.cer", generatedAt));
        using var secondEntra = DecodeScriptPayload(generator.GenerateEntraScript(second, @"C:\public.cer", generatedAt));
        Assert.Equal(
            firstEntra.RootElement.GetProperty("ApplicationDisplayName").GetString(),
            stableEntra.RootElement.GetProperty("ApplicationDisplayName").GetString());
        Assert.NotEqual(
            firstEntra.RootElement.GetProperty("ApplicationDisplayName").GetString(),
            secondEntra.RootElement.GetProperty("ApplicationDisplayName").GetString());

        using var firstExchange = DecodeScriptPayload(generator.GenerateExchangeScript(first, generatedAt));
        using var secondExchange = DecodeScriptPayload(generator.GenerateExchangeScript(second, generatedAt));
        Assert.NotEqual(
            firstExchange.RootElement.GetProperty("GroupName").GetString(),
            secondExchange.RootElement.GetProperty("GroupName").GetString());
        Assert.NotEqual(
            firstExchange.RootElement.GetProperty("ScopeName").GetString(),
            secondExchange.RootElement.GetProperty("ScopeName").GetString());
        Assert.NotEqual(
            firstExchange.RootElement.GetProperty("AssignmentName").GetString(),
            secondExchange.RootElement.GetProperty("AssignmentName").GetString());
    }

    [Fact]
    public async Task Wizard_resumes_after_restart_backtracks_and_cancel_preserves_active_configuration()
    {
        await using var context = await SetupTestContext.CreateAsync();
        var active = MicrosoftIdentityConfiguration.Create(
            Guid.NewGuid(),
            Guid.NewGuid(),
            context.Certificate);
        context.Database.SaveMicrosoftIdentityConfiguration(active);

        var state = context.Setup.Begin(MicrosoftSetupMode.ExistingApplication);
        Assert.Equal(MicrosoftSetupStep.Certificate, state.Step);
        state = context.Setup.SelectCertificate(context.Certificate);
        Assert.Equal(MicrosoftSetupStep.MicrosoftApplication, state.Step);

        var restarted = context.CreateSetupService();
        Assert.Equal(MicrosoftSetupStep.MicrosoftApplication, restarted.GetState().Step);
        Assert.Equal(MicrosoftSetupStep.Certificate, restarted.Back().Step);

        restarted.Cancel();
        var stillActive = context.Database.GetMicrosoftIdentityConfiguration();
        Assert.NotNull(stillActive);
        Assert.Equal(active.TenantId, stillActive.TenantId);
        Assert.Equal(active.ClientId, stillActive.ClientId);
        Assert.True(context.Certificates.Validate(context.Certificate).IsUsable);
    }

    [Fact]
    public async Task Direct_connection_verification_uses_active_configuration_without_repair_or_mail_submission()
    {
        await using var context = await SetupTestContext.CreateAsync();
        var configuration = MicrosoftIdentityConfiguration.Create(
            Guid.NewGuid(),
            Guid.NewGuid(),
            context.Certificate);
        var completed = CompletedState(context, configuration, Guid.NewGuid());
        context.Database.ActivateMicrosoftConfiguration(
            configuration,
            completed.SenderMailbox!,
            completed);
        var before = context.Database.GetActiveMicrosoftConfiguration()!;

        var result = await context.Setup.VerifyActiveConnectionAsync();

        Assert.True(result.Succeeded);
        Assert.Equal(MicrosoftSetupStep.Complete, result.State.Step);
        Assert.Equal(MicrosoftSetupCandidateLifecycle.Activated, result.State.Lifecycle);
        Assert.Equal(completed.ServicePrincipalObjectId, result.State.ServicePrincipalObjectId);
        Assert.Contains("No email was sent", result.Message, StringComparison.Ordinal);
        Assert.Equal(configuration.TenantId, context.IdentityFactory.LastConfiguration?.TenantId);
        Assert.Equal(configuration.ClientId, context.IdentityFactory.LastConfiguration?.ClientId);
        Assert.Equal(
            configuration.Certificate.Thumbprint,
            context.IdentityFactory.LastConfiguration?.Certificate.Thumbprint);
        Assert.Equal(
            configuration.Certificate.StoreLocation,
            context.IdentityFactory.LastConfiguration?.Certificate.StoreLocation);
        Assert.DoesNotContain(context.Server.Commands, command => command.StartsWith("MAIL FROM", StringComparison.OrdinalIgnoreCase));
        Assert.DoesNotContain(context.Server.Commands, command => command.StartsWith("RCPT TO", StringComparison.OrdinalIgnoreCase));
        Assert.DoesNotContain(context.Server.Commands, command => string.Equals(command, "DATA", StringComparison.OrdinalIgnoreCase));
        Assert.True(context.Server.QuitReceived);
        var after = context.Database.GetActiveMicrosoftConfiguration()!;
        Assert.Equal(before.ActivationId, after.ActivationId);
        Assert.Equal(before.Fingerprint, after.Fingerprint);
        Assert.Equal(
            MicrosoftRuntimeReadiness.Ready,
            MicrosoftRuntimeReadinessPolicy.Evaluate(
                configured: true,
                after.Fingerprint,
                context.IdentityRuntime,
                context.ExchangeRuntime));
        var exchange = context.ExchangeRuntime.GetCompletedSnapshot(after.Fingerprint);
        Assert.True(exchange.XOAuth2Authenticated);
        Assert.True(exchange.SenderAuthorized);
        Assert.False(exchange.MessageAccepted);
    }

    [Fact]
    public async Task Direct_connection_verification_failure_is_sanitized_and_preserves_active_configuration()
    {
        await using var context = await SetupTestContext.CreateAsync(new FakeExchangeScenario
        {
            AuthResult = "535 5.7.3 Authentication unsuccessful bearer should-not-appear",
        });
        var configuration = MicrosoftIdentityConfiguration.Create(
            Guid.NewGuid(),
            Guid.NewGuid(),
            context.Certificate);
        var completed = CompletedState(context, configuration, Guid.NewGuid());
        context.Database.ActivateMicrosoftConfiguration(
            configuration,
            completed.SenderMailbox!,
            completed);
        var before = context.Database.GetActiveMicrosoftConfiguration()!;

        var result = await context.Setup.VerifyActiveConnectionAsync();

        Assert.False(result.Succeeded);
        Assert.Equal(MicrosoftSetupStep.Complete, result.State.Step);
        Assert.Contains("XOAUTH2 authentication", result.Message, StringComparison.Ordinal);
        Assert.DoesNotContain("should-not-appear", result.Message, StringComparison.Ordinal);
        Assert.DoesNotContain("bearer", result.Message, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain(context.Server.Commands, command => command.StartsWith("MAIL FROM", StringComparison.OrdinalIgnoreCase));
        Assert.DoesNotContain(context.Server.Commands, command => command.StartsWith("RCPT TO", StringComparison.OrdinalIgnoreCase));
        Assert.DoesNotContain(context.Server.Commands, command => string.Equals(command, "DATA", StringComparison.OrdinalIgnoreCase));
        var after = context.Database.GetActiveMicrosoftConfiguration()!;
        Assert.Equal(before.ActivationId, after.ActivationId);
        Assert.Equal(before.Fingerprint, after.Fingerprint);
        Assert.Equal(
            MicrosoftRuntimeReadiness.NeedsAttention,
            MicrosoftRuntimeReadinessPolicy.Evaluate(
                configured: true,
                after.Fingerprint,
                context.IdentityRuntime,
                context.ExchangeRuntime));
    }

    [Fact]
    public async Task Repair_preserves_service_principal_only_for_the_same_active_configuration()
    {
        await using var context = await SetupTestContext.CreateAsync();
        var configuration = MicrosoftIdentityConfiguration.Create(
            Guid.NewGuid(),
            Guid.NewGuid(),
            context.Certificate);
        var servicePrincipal = Guid.NewGuid();
        var completed = CompletedState(context, configuration, servicePrincipal);
        context.Database.ActivateMicrosoftConfiguration(
            configuration,
            completed.SenderMailbox!,
            completed);

        var repair = context.Setup.BeginRepair();

        Assert.Equal(MicrosoftSetupMode.ExistingApplication, repair.Mode);
        Assert.Equal(MicrosoftSetupStep.MicrosoftApplication, repair.Step);
        Assert.Equal(servicePrincipal, repair.ServicePrincipalObjectId);
        Assert.Equal(completed.ActivationId, repair.ActivationId);

        var replacement = context.Setup.Begin(MicrosoftSetupMode.NewApplication);
        Assert.Null(replacement.ServicePrincipalObjectId);
        Assert.NotEqual(completed.ActivationId, replacement.ActivationId);
    }

    [Fact]
    public async Task Pasted_results_are_bounded_strict_data_and_require_zero_permissions_and_exact_role()
    {
        await using var context = await SetupTestContext.CreateAsync();
        context.Setup.Begin(MicrosoftSetupMode.NewApplication);
        context.Setup.SelectCertificate(context.Certificate);
        var tenant = Guid.NewGuid();
        var client = Guid.NewGuid();
        var servicePrincipal = Guid.NewGuid();

        var state = context.Setup.ApplyEntraResult(
            $$"""{"TenantId":"{{tenant:D}}","ClientId":"{{client:D}}","ServicePrincipalObjectId":"{{servicePrincipal:D}}","ApiPermissionEntryCount":0}""");
        Assert.Equal(MicrosoftSetupStep.ExchangePermission, state.Step);
        Assert.Equal(client, state.ClientId);

        context.Setup.SetSenderMailbox("Scanner@Example.com");
        state = context.Setup.ApplyExchangeResult(
            """{"ServicePrincipalConfigured":true,"ScopeConfigured":true,"Role":"Application SMTP.SendAsApp","SenderInScope":true}""");
        Assert.Equal(MicrosoftSetupStep.VerifyIdentity, state.Step);
        Assert.Equal("scanner@example.com", state.SenderMailbox);

        Assert.Throws<ArgumentException>(() => context.Setup.ApplyEntraResult(
            new string('x', MicrosoftSetupValidation.MaximumSetupResultBytes + 1)));
        Assert.Throws<ArgumentException>(() => context.Setup.ApplyEntraResult(
            $$"""{"TenantId":"{{tenant:D}}","ClientId":"{{client:D}}","ServicePrincipalObjectId":"{{servicePrincipal:D}}","ApiPermissionEntryCount":0,"Unexpected":"code"}"""));
        Assert.Throws<InvalidOperationException>(() => context.Setup.ApplyEntraResult(
            $$"""{"TenantId":"{{tenant:D}}","ClientId":"{{client:D}}","ServicePrincipalObjectId":"{{servicePrincipal:D}}","ApiPermissionEntryCount":1}"""));
        Assert.Throws<InvalidOperationException>(() => context.Setup.ApplyExchangeResult(
            """{"ServicePrincipalConfigured":true,"ScopeConfigured":true,"Role":"Application Mail.Send","SenderInScope":true}"""));
    }

    [Fact]
    public async Task Candidate_identity_and_exchange_are_verified_before_atomic_activation()
    {
        await using var context = await SetupTestContext.CreateAsync();
        var original = MicrosoftIdentityConfiguration.Create(Guid.NewGuid(), Guid.NewGuid(), context.Certificate);
        context.Database.SaveMicrosoftIdentityConfiguration(original);
        var candidateTenant = Guid.NewGuid();
        var candidateClient = Guid.NewGuid();
        PrepareCandidate(context, candidateTenant, candidateClient);
        var candidateActivationId = Assert.IsType<Guid>(context.Setup.GetState().ActivationId);

        var identity = await context.Setup.VerifyIdentityAsync();
        Assert.True(identity.Succeeded);
        Assert.Equal(MicrosoftSetupStep.VerifyExchange, identity.State.Step);
        Assert.Equal(original.ClientId, context.Database.GetMicrosoftIdentityConfiguration()!.ClientId);

        var exchange = await context.Setup.VerifyExchangeAsync();
        Assert.True(exchange.Succeeded);
        Assert.Equal(MicrosoftSetupStep.TestMessage, exchange.State.Step);
        var active = context.Database.GetActiveMicrosoftConfiguration();
        Assert.NotNull(active);
        Assert.Equal(candidateTenant, active.Identity.TenantId);
        Assert.Equal(candidateClient, active.Identity.ClientId);
        Assert.Equal("scanner@example.com", context.Database.GetMicrosoftAuthorizedSender());
        Assert.Equal(candidateActivationId, active.ActivationId);
        Assert.Equal(
            ExchangeDeliveryStatus.Healthy,
            context.ExchangeRuntime.GetCompletedSnapshot(active.Fingerprint).Status);

        var completed = context.Setup.CompleteNativeSetupAfterVerifiedExchange();
        Assert.Equal(MicrosoftSetupStep.Complete, completed.Step);
        Assert.True(completed.TestMessageAccepted);
    }

    [Fact]
    public async Task Candidate_token_failure_does_not_replace_working_configuration()
    {
        await using var context = await SetupTestContext.CreateAsync();
        var original = MicrosoftIdentityConfiguration.Create(Guid.NewGuid(), Guid.NewGuid(), context.Certificate);
        context.Database.SaveMicrosoftIdentityConfiguration(original);
        var originalActivationId = context.Database.GetActiveMicrosoftConfiguration()!.ActivationId;
        PrepareCandidate(context, Guid.NewGuid(), Guid.NewGuid());
        context.IdentityFactory.Error = new MicrosoftIdentityException(
            MicrosoftIdentityErrorCategory.CredentialRejected,
            "Microsoft rejected the candidate certificate.",
            "AADSTS700027",
            "safe-correlation");

        var result = await context.Setup.VerifyIdentityAsync();

        Assert.False(result.Succeeded);
        Assert.Equal("AADSTS700027", result.TechnicalCode);
        Assert.Equal("safe-correlation", result.CorrelationId);
        Assert.Equal(original.ClientId, context.Database.GetMicrosoftIdentityConfiguration()!.ClientId);
        Assert.Equal(originalActivationId, context.Database.GetActiveMicrosoftConfiguration()!.ActivationId);
        Assert.Equal(MicrosoftSetupStep.VerifyIdentity, context.Setup.GetState().Step);
    }

    [Fact]
    public async Task Native_results_are_rejected_after_candidate_replacement_or_revision_change()
    {
        await using var context = await SetupTestContext.CreateAsync();
        PrepareNativeCandidateStart(context);
        var sessionA = context.Setup.CaptureNativeCandidate();
        var entra = new EntraSetupResult(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), 0);

        context.Setup.Begin(MicrosoftSetupMode.NewApplication);
        context.Setup.SelectCertificate(context.Certificate);
        context.Setup.SetSenderMailbox("replacement@example.com");
        Assert.Throws<MicrosoftSetupConcurrencyException>(() =>
            context.Setup.ApplyNativeEntraResult(sessionA, entra));
        Assert.False(context.QueueDeliveryActivation.IsActivated);

        PrepareNativeCandidateStart(context);
        sessionA = context.Setup.CaptureNativeCandidate();
        var preEntraFingerprint = sessionA.ConfigurationFingerprint;
        sessionA = context.Setup.ApplyNativeEntraResult(sessionA, entra);
        Assert.NotEqual(preEntraFingerprint, sessionA.ConfigurationFingerprint);
        context.Setup.Begin(MicrosoftSetupMode.NewApplication);
        context.Setup.SelectCertificate(context.Certificate);
        context.Setup.SetSenderMailbox("replacement@example.com");
        Assert.Throws<MicrosoftSetupConcurrencyException>(() =>
            context.Setup.ApplyNativeExchangeResult(sessionA, ValidExchangeResult()));
        Assert.False(context.QueueDeliveryActivation.IsActivated);

        PrepareNativeCandidateStart(context);
        sessionA = context.Setup.CaptureNativeCandidate();
        context.Setup.SetSenderMailbox("scanner@example.com");
        Assert.Throws<MicrosoftSetupConcurrencyException>(() =>
            context.Setup.ApplyNativeEntraResult(sessionA, entra));
        Assert.False(context.QueueDeliveryActivation.IsActivated);
    }

    [Fact]
    public async Task Native_final_acceptance_cannot_activate_a_cancelled_candidate()
    {
        var finalResponseRelease = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
        var scenario = new FakeExchangeScenario { FinalResponseRelease = finalResponseRelease.Task };
        await using var context = await SetupTestContext.CreateAsync(scenario);
        var original = MicrosoftIdentityConfiguration.Create(Guid.NewGuid(), Guid.NewGuid(), context.Certificate);
        context.Database.SaveMicrosoftIdentityConfiguration(original);
        var originalActivation = context.Database.GetActiveMicrosoftConfiguration()!.ActivationId;
        PrepareNativeCandidateStart(context);
        var candidate = context.Setup.CaptureNativeCandidate();
        candidate = context.Setup.ApplyNativeEntraResult(
            candidate,
            new EntraSetupResult(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), 0));
        candidate = context.Setup.ApplyNativeExchangeResult(candidate, ValidExchangeResult());

        var verification = context.Setup.VerifyAndActivateNativeAsync(candidate);
        await context.Server.DataReceivedSignal.Task.WaitAsync(TimeSpan.FromSeconds(10));
        context.Setup.Cancel();
        finalResponseRelease.SetResult();

        await Assert.ThrowsAsync<MicrosoftSetupConcurrencyException>(() => verification);
        var active = context.Database.GetActiveMicrosoftConfiguration()!;
        Assert.Equal(originalActivation, active.ActivationId);
        Assert.Equal(original.ClientId, active.Identity.ClientId);
        Assert.False(context.QueueDeliveryActivation.IsActivated);
    }

    [Fact]
    public async Task Cancel_after_final_250_before_activation_transaction_prevents_activation()
    {
        using var activationReached = new ManualResetEventSlim();
        using var releaseActivation = new ManualResetEventSlim();
        var hooks = new MicrosoftSetupPersistenceHooks
        {
            BeforeActivationPersistence = () =>
            {
                activationReached.Set();
                releaseActivation.Wait();
            },
        };
        await using var context = await SetupTestContext.CreateAsync(persistenceHooks: hooks);
        var original = MicrosoftIdentityConfiguration.Create(Guid.NewGuid(), Guid.NewGuid(), context.Certificate);
        context.Database.SaveMicrosoftIdentityConfiguration(original);
        var originalActivation = context.Database.GetActiveMicrosoftConfiguration()!.ActivationId;
        var candidate = PrepareNativeValidatedCandidate(context);

        var verification = context.Setup.VerifyAndActivateNativeAsync(candidate);
        Assert.True(activationReached.Wait(TimeSpan.FromSeconds(10)));
        var cancelled = context.Setup.CancelNativeCandidate(candidate);
        releaseActivation.Set();

        Assert.Equal(MicrosoftSetupCancellationOutcome.Cancelled, cancelled.Outcome);
        await Assert.ThrowsAsync<MicrosoftSetupConcurrencyException>(() => verification);
        Assert.Equal(MicrosoftSetupCandidateLifecycle.Cancelled, context.Setup.GetState().Lifecycle);
        Assert.Equal(originalActivation, context.Database.GetActiveMicrosoftConfiguration()!.ActivationId);
        Assert.False(context.QueueDeliveryActivation.IsActivated);
    }

    [Fact]
    public async Task Activation_commit_wins_over_later_cancel_without_false_rollback()
    {
        using var activationCommitted = new ManualResetEventSlim();
        using var releaseResponse = new ManualResetEventSlim();
        var hooks = new MicrosoftSetupPersistenceHooks
        {
            AfterActivationCommit = () =>
            {
                activationCommitted.Set();
                releaseResponse.Wait();
            },
        };
        await using var context = await SetupTestContext.CreateAsync(persistenceHooks: hooks);
        var candidate = PrepareNativeValidatedCandidate(context);

        var verification = context.Setup.VerifyAndActivateNativeAsync(candidate);
        Assert.True(activationCommitted.Wait(TimeSpan.FromSeconds(10)));
        var cancellation = context.Setup.CancelNativeCandidate(candidate);
        releaseResponse.Set();
        var result = await verification;

        Assert.True(result.Succeeded);
        Assert.Equal(MicrosoftSetupCancellationOutcome.AlreadyActivated, cancellation.Outcome);
        Assert.Equal(candidate.ActivationId, context.Database.GetActiveMicrosoftConfiguration()!.ActivationId);
        Assert.Equal(MicrosoftSetupCandidateLifecycle.Activated, context.Setup.GetState().Lifecycle);
    }

    [Fact]
    public async Task Late_Entra_and_Exchange_results_are_rejected_after_persisted_cancel()
    {
        using var entraReached = new ManualResetEventSlim();
        using var releaseEntra = new ManualResetEventSlim();
        var entraHooks = new MicrosoftSetupPersistenceHooks
        {
            BeforeEntraResultPersistence = () =>
            {
                entraReached.Set();
                releaseEntra.Wait();
            },
        };
        await using (var context = await SetupTestContext.CreateAsync(persistenceHooks: entraHooks))
        {
            PrepareNativeCandidateStart(context);
            var candidate = context.Setup.CaptureNativeCandidate();
            var persistence = Task.Run(() => context.Setup.ApplyNativeEntraResult(
                candidate,
                new EntraSetupResult(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), 0)));
            Assert.True(entraReached.Wait(TimeSpan.FromSeconds(10)));
            Assert.Equal(
                MicrosoftSetupCancellationOutcome.Cancelled,
                context.Setup.CancelNativeCandidate(candidate).Outcome);
            releaseEntra.Set();
            await Assert.ThrowsAsync<MicrosoftSetupConcurrencyException>(() => persistence);
            Assert.False(context.Setup.GetState().EntraResultValidated);
        }

        using var exchangeReached = new ManualResetEventSlim();
        using var releaseExchange = new ManualResetEventSlim();
        var exchangeHooks = new MicrosoftSetupPersistenceHooks
        {
            BeforeExchangeResultPersistence = () =>
            {
                exchangeReached.Set();
                releaseExchange.Wait();
            },
        };
        await using (var context = await SetupTestContext.CreateAsync(persistenceHooks: exchangeHooks))
        {
            PrepareNativeCandidateStart(context);
            var candidate = context.Setup.CaptureNativeCandidate();
            candidate = context.Setup.ApplyNativeEntraResult(
                candidate,
                new EntraSetupResult(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), 0));
            var persistence = Task.Run(() => context.Setup.ApplyNativeExchangeResult(candidate, ValidExchangeResult()));
            Assert.True(exchangeReached.Wait(TimeSpan.FromSeconds(10)));
            Assert.Equal(
                MicrosoftSetupCancellationOutcome.Cancelled,
                context.Setup.CancelNativeCandidate(candidate).Outcome);
            releaseExchange.Set();
            await Assert.ThrowsAsync<MicrosoftSetupConcurrencyException>(() => persistence);
            Assert.False(context.Setup.GetState().ExchangeResultValidated);
        }
    }

    [Fact]
    public async Task Candidate_cancellation_is_idempotent_and_never_cancels_a_replacement()
    {
        await using var context = await SetupTestContext.CreateAsync();
        PrepareNativeCandidateStart(context);
        var candidateA = context.Setup.CaptureNativeCandidate();

        var first = context.Setup.CancelNativeCandidate(candidateA);
        var second = context.Setup.CancelNativeCandidate(candidateA);
        Assert.Equal(MicrosoftSetupCancellationOutcome.Cancelled, first.Outcome);
        Assert.Equal(MicrosoftSetupCancellationOutcome.AlreadyCancelled, second.Outcome);

        PrepareNativeCandidateStart(context);
        var candidateB = context.Setup.CaptureNativeCandidate();
        var lateA = context.Setup.CancelNativeCandidate(candidateA);
        Assert.Equal(MicrosoftSetupCancellationOutcome.Replaced, lateA.Outcome);
        Assert.Equal(candidateB.ActivationId, context.Setup.GetState().ActivationId);
        Assert.Equal(MicrosoftSetupCandidateLifecycle.Active, context.Setup.GetState().Lifecycle);
    }

    [Fact]
    public async Task Native_final_acceptance_atomically_activates_only_the_bound_candidate()
    {
        await using var context = await SetupTestContext.CreateAsync();
        PrepareNativeCandidateStart(context);
        var candidate = context.Setup.CaptureNativeCandidate();
        var tenant = Guid.NewGuid();
        var client = Guid.NewGuid();
        candidate = context.Setup.ApplyNativeEntraResult(
            candidate,
            new EntraSetupResult(tenant, client, Guid.NewGuid(), 0));
        candidate = context.Setup.ApplyNativeExchangeResult(candidate, ValidExchangeResult());

        var result = await context.Setup.VerifyAndActivateNativeAsync(candidate);

        Assert.True(result.Succeeded);
        Assert.Equal(MicrosoftSetupStep.Complete, result.State.Step);
        Assert.True(result.State.ExchangeValidated);
        Assert.True(result.State.TestMessageAccepted);
        var active = context.Database.GetActiveMicrosoftConfiguration()!;
        Assert.Equal(candidate.ActivationId, active.ActivationId);
        Assert.Equal(tenant, active.Identity.TenantId);
        Assert.Equal(client, active.Identity.ClientId);

        context.Setup.Cancel();
        var afterLateCancellation = context.Database.GetActiveMicrosoftConfiguration()!;
        Assert.Equal(candidate.ActivationId, afterLateCancellation.ActivationId);
        Assert.Equal(client, afterLateCancellation.Identity.ClientId);
    }

    [Fact]
    public async Task Existing_queue_worker_wakes_after_authoritative_activation_without_service_restart()
    {
        await using var context = await SetupTestContext.CreateAsync();
        var deliveryStarted = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
        var provider = new ScriptedDeliveryProvider((_, _, _) =>
        {
            deliveryStarted.TrySetResult();
            return Task.FromResult(DeliveryResult.Succeeded());
        });
        var queue = CreateQueueLifecycle(context, enabled: true, provider);
        await queue.HostedService.StartAsync(CancellationToken.None);

        Assert.True(queue.Worker.IsRunning);
        Assert.False(context.QueueDeliveryActivation.IsActivated);
        var queued = await EnqueueAsync(queue);
        await Task.Delay(200);
        Assert.Empty(provider.MessageIds);

        var candidate = PrepareNativeValidatedCandidate(context);
        var activation = await context.Setup.VerifyAndActivateNativeAsync(candidate);

        Assert.True(activation.Succeeded);
        Assert.True(context.QueueDeliveryActivation.IsActivated);
        await deliveryStarted.Task.WaitAsync(TimeSpan.FromSeconds(5));
        await WaitUntilAsync(
            () => context.Database.GetQueuedMessages().Single(message => message.Id == queued.Id).State == QueueState.Delivered,
            TimeSpan.FromSeconds(5));
        context.QueueDeliveryActivation.Activate();
        await Task.Delay(200);
        Assert.Equal([queued.Id], provider.MessageIds);
        Assert.True(queue.Worker.IsRunning);

        using var stop = new CancellationTokenSource(TimeSpan.FromSeconds(2));
        await queue.HostedService.StopAsync(stop.Token);
        Assert.False(queue.Worker.IsRunning);
    }

    [Fact]
    public async Task Queue_disabled_remains_disabled_after_authoritative_activation()
    {
        await using var context = await SetupTestContext.CreateAsync();
        var provider = new ScriptedDeliveryProvider(DeliveryResult.Succeeded());
        var queue = CreateQueueLifecycle(context, enabled: false, provider);
        await queue.HostedService.StartAsync(CancellationToken.None);
        var queued = await EnqueueAsync(queue);

        var candidate = PrepareNativeValidatedCandidate(context);
        var activation = await context.Setup.VerifyAndActivateNativeAsync(candidate);

        Assert.True(activation.Succeeded);
        Assert.True(context.QueueDeliveryActivation.IsActivated);
        Assert.False(queue.Worker.IsRunning);
        await Task.Delay(200);
        Assert.Empty(provider.MessageIds);
        Assert.Equal(
            QueueState.Queued,
            context.Database.GetQueuedMessages().Single(message => message.Id == queued.Id).State);
        await queue.HostedService.StopAsync(CancellationToken.None);
    }

    [Fact]
    public async Task Queue_worker_with_preexisting_active_configuration_retains_startup_behavior()
    {
        await using var context = await SetupTestContext.CreateAsync();
        var configuration = MicrosoftIdentityConfiguration.Create(
            Guid.NewGuid(),
            Guid.NewGuid(),
            context.Certificate);
        var completed = CompletedState(context, configuration, Guid.NewGuid());
        context.Database.ActivateMicrosoftConfiguration(
            configuration,
            completed.SenderMailbox!,
            completed);
        var deliveryStarted = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
        var provider = new ScriptedDeliveryProvider((_, _, _) =>
        {
            deliveryStarted.TrySetResult();
            return Task.FromResult(DeliveryResult.Succeeded());
        });
        var queue = CreateQueueLifecycle(context, enabled: true, provider);
        var queued = await EnqueueAsync(queue);

        await queue.HostedService.StartAsync(CancellationToken.None);

        Assert.True(context.QueueDeliveryActivation.IsActivated);
        await deliveryStarted.Task.WaitAsync(TimeSpan.FromSeconds(5));
        await WaitUntilAsync(
            () => context.Database.GetQueuedMessages().Single(message => message.Id == queued.Id).State == QueueState.Delivered,
            TimeSpan.FromSeconds(5));
        await queue.HostedService.StopAsync(CancellationToken.None);
    }

    [Fact]
    public async Task Queue_worker_waiting_for_activation_stops_promptly()
    {
        await using var context = await SetupTestContext.CreateAsync();
        var queue = CreateQueueLifecycle(
            context,
            enabled: true,
            new ScriptedDeliveryProvider(DeliveryResult.Succeeded()));
        await queue.HostedService.StartAsync(CancellationToken.None);
        Assert.True(queue.Worker.IsRunning);
        Assert.False(context.QueueDeliveryActivation.IsActivated);

        using var stop = new CancellationTokenSource(TimeSpan.FromSeconds(2));
        await queue.HostedService.StopAsync(stop.Token);

        Assert.False(stop.IsCancellationRequested);
        Assert.False(queue.Worker.IsRunning);
    }

    [Fact]
    public async Task Identical_configuration_reactivation_gets_a_fresh_activation_epoch()
    {
        await using var context = await SetupTestContext.CreateAsync();
        var first = MicrosoftIdentityConfiguration.Create(Guid.NewGuid(), Guid.NewGuid(), context.Certificate);
        var firstState = ReadyState() with
        {
            Certificate = context.Certificate,
            TenantId = first.TenantId,
            ClientId = first.ClientId,
            SenderMailbox = "scanner@example.com",
            ActivationId = Guid.NewGuid(),
        };
        context.Database.ActivateMicrosoftConfiguration(first, "scanner@example.com", firstState);
        var firstActive = context.Database.GetActiveMicrosoftConfiguration()!;

        context.Database.SaveMicrosoftIdentityConfiguration(MicrosoftIdentityConfiguration.Create(
            Guid.NewGuid(),
            Guid.NewGuid(),
            context.Certificate));
        var middle = context.Database.GetActiveMicrosoftConfiguration()!;
        context.Database.SaveMicrosoftIdentityConfiguration(first);
        var reactivated = context.Database.GetActiveMicrosoftConfiguration()!;

        Assert.NotEqual(firstActive.ActivationId, middle.ActivationId);
        Assert.NotEqual(firstActive.ActivationId, reactivated.ActivationId);
        Assert.Equal(firstActive.ConfigurationFingerprint, reactivated.ConfigurationFingerprint);
        Assert.NotEqual(firstActive.Fingerprint, reactivated.Fingerprint);
        Assert.Equal(
            ExchangeDeliveryStatus.NotTested,
            context.ExchangeRuntime.GetCompletedSnapshot(reactivated.Fingerprint).Status);
    }

    [Fact]
    public async Task Smtp_authorization_failure_does_not_replace_working_configuration()
    {
        await using var context = await SetupTestContext.CreateAsync(new FakeExchangeScenario
        {
            AuthResult = "535 5.7.3 Authentication unsuccessful",
        });
        var original = MicrosoftIdentityConfiguration.Create(Guid.NewGuid(), Guid.NewGuid(), context.Certificate);
        context.Database.SaveMicrosoftIdentityConfiguration(original);
        PrepareCandidate(context, Guid.NewGuid(), Guid.NewGuid());
        Assert.True((await context.Setup.VerifyIdentityAsync()).Succeeded);

        var result = await context.Setup.VerifyExchangeAsync();

        Assert.False(result.Succeeded);
        Assert.Equal("Authentication · SMTP 535", result.TechnicalCode);
        Assert.Contains("propagation is not certain", result.Message, StringComparison.Ordinal);
        Assert.Contains("retried briefly", result.Message, StringComparison.Ordinal);
        Assert.Contains("If the problem persists", result.Message, StringComparison.Ordinal);
        Assert.Contains("tenant and mailbox SMTP AUTH settings", result.Message, StringComparison.Ordinal);
        Assert.True(Guid.TryParse(result.CorrelationId, out _));
        Assert.Equal(4, context.Server.ConnectionCount);
        Assert.DoesNotContain(context.Server.Commands, command =>
            command.StartsWith("MAIL", StringComparison.OrdinalIgnoreCase) ||
            command.StartsWith("RCPT", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(command, "DATA", StringComparison.OrdinalIgnoreCase));
        Assert.Equal(original.ClientId, context.Database.GetMicrosoftIdentityConfiguration()!.ClientId);
        Assert.Equal(MicrosoftSetupStep.VerifyExchange, context.Setup.GetState().Step);
        Assert.False(context.QueueDeliveryActivation.IsActivated);
    }

    [Fact]
    public async Task Setup_smtp_verification_retries_bounded_535_and_succeeds_after_propagation()
    {
        await using var context = await SetupTestContext.CreateAsync(new FakeExchangeScenario
        {
            AuthResults =
            [
                "535 5.7.3 Authentication unsuccessful",
                "235 2.7.0 Authentication successful",
            ],
        });
        PrepareCandidate(context, Guid.NewGuid(), Guid.NewGuid());
        Assert.True((await context.Setup.VerifyIdentityAsync()).Succeeded);

        var result = await context.Setup.VerifyExchangeAsync();

        Assert.True(result.Succeeded);
        Assert.Equal(2, context.Server.ConnectionCount);
        var authIndexes = context.Server.Commands
            .Select((command, index) => (command, index))
            .Where(item => item.command == "AUTH XOAUTH2 [REDACTED]")
            .Select(item => item.index)
            .ToArray();
        Assert.Equal(2, authIndexes.Length);
        var mailIndex = context.Server.Commands
            .Select((command, index) => (command, index))
            .Single(item => item.command.StartsWith("MAIL FROM:", StringComparison.OrdinalIgnoreCase))
            .index;
        Assert.True(mailIndex > authIndexes[1]);
    }

    [Fact]
    public async Task Setup_smtp_verification_does_not_propagation_retry_tls_failure()
    {
        await using var context = await SetupTestContext.CreateAsync(new FakeExchangeScenario
        {
            StartTls = "454 4.7.0 TLS not available",
        });
        PrepareCandidate(context, Guid.NewGuid(), Guid.NewGuid());
        Assert.True((await context.Setup.VerifyIdentityAsync()).Succeeded);

        var result = await context.Setup.VerifyExchangeAsync();

        Assert.False(result.Succeeded);
        Assert.Equal(1, context.Server.ConnectionCount);
        Assert.Contains("SMTP 454", result.TechnicalCode, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task Setup_smtp_verification_does_not_retry_non_535_auth_response()
    {
        await using var context = await SetupTestContext.CreateAsync(new FakeExchangeScenario
        {
            AuthResult = "550 5.7.1 Not authorized",
        });
        PrepareCandidate(context, Guid.NewGuid(), Guid.NewGuid());
        Assert.True((await context.Setup.VerifyIdentityAsync()).Succeeded);

        var result = await context.Setup.VerifyExchangeAsync();

        Assert.False(result.Succeeded);
        Assert.Equal(1, context.Server.ConnectionCount);
    }

    [Fact]
    public async Task Setup_smtp_propagation_wait_is_cancellable_without_sending_mail()
    {
        await using var context = await SetupTestContext.CreateAsync(
            new FakeExchangeScenario { AuthResult = "535 5.7.3 Authentication unsuccessful" },
            smtpPropagationRetryDelays: [TimeSpan.FromMinutes(1)]);
        PrepareCandidate(context, Guid.NewGuid(), Guid.NewGuid());
        Assert.True((await context.Setup.VerifyIdentityAsync()).Succeeded);
        using var cancellation = new CancellationTokenSource(TimeSpan.FromMilliseconds(250));

        await Assert.ThrowsAnyAsync<OperationCanceledException>(() =>
            context.Setup.VerifyExchangeAsync(cancellation.Token));

        Assert.Equal(1, context.Server.ConnectionCount);
        Assert.DoesNotContain(context.Server.Commands, command =>
            command.StartsWith("MAIL", StringComparison.OrdinalIgnoreCase) ||
            command.StartsWith("RCPT", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(command, "DATA", StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public async Task Test_message_uses_active_exchange_provider_and_completes_only_after_final_acceptance()
    {
        await using var context = await SetupTestContext.CreateAsync();
        var configuration = MicrosoftIdentityConfiguration.Create(Guid.NewGuid(), Guid.NewGuid(), context.Certificate);
        var state = ReadyState() with
        {
            Certificate = context.Certificate,
            TenantId = configuration.TenantId,
            ClientId = configuration.ClientId,
            Step = MicrosoftSetupStep.TestMessage,
            IdentityValidated = true,
            ExchangeValidated = true,
        };
        context.Database.ActivateMicrosoftConfiguration(configuration, "scanner@example.com", state);

        var result = await context.Setup.SendTestMessageAsync("administrator@example.com");

        Assert.True(result.Succeeded);
        Assert.Equal(MicrosoftSetupStep.Complete, result.State.Step);
        Assert.True(result.State.TestMessageAccepted);
        Assert.True(context.Server.DataCommandReceived);
    }

    [Fact]
    public async Task Setup_schema_persists_only_safe_progress_and_sender_metadata()
    {
        await using var context = await SetupTestContext.CreateAsync();
        context.Setup.Begin(MicrosoftSetupMode.NewApplication);
        context.Setup.SelectCertificate(context.Certificate);

        using var connection = context.Database.OpenConnectionForDiagnostics();
        using var command = connection.CreateCommand();
        command.CommandText = "PRAGMA table_info(MicrosoftSetupState);";
        using var reader = command.ExecuteReader();
        var columns = new List<string>();
        while (reader.Read())
        {
            columns.Add(reader.GetString(1));
        }

        Assert.Contains("ServicePrincipalObjectId", columns);
        Assert.Contains("SenderMailbox", columns);
        Assert.DoesNotContain(columns, name => name.Contains("Token", StringComparison.OrdinalIgnoreCase));
        Assert.DoesNotContain(columns, name => name.Contains("Password", StringComparison.OrdinalIgnoreCase));
        Assert.DoesNotContain(columns, name => name.Contains("Private", StringComparison.OrdinalIgnoreCase));
        Assert.DoesNotContain(columns, name => name.Contains("Script", StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public async Task Milestone_three_schema_migrates_to_setup_state_without_losing_active_identity()
    {
        await using var context = await SetupTestContext.CreateAsync();
        var active = MicrosoftIdentityConfiguration.Create(Guid.NewGuid(), Guid.NewGuid(), context.Certificate);
        context.Database.SaveMicrosoftIdentityConfiguration(active);
        using (var connection = context.Database.OpenConnectionForDiagnostics())
        using (var command = connection.CreateCommand())
        {
            command.CommandText =
                """
                DROP TABLE MicrosoftSetupState;
                ALTER TABLE MicrosoftIdentityConfiguration RENAME TO MicrosoftIdentityConfiguration_M4;
                CREATE TABLE MicrosoftIdentityConfiguration (
                    Id INTEGER PRIMARY KEY CHECK (Id = 1),
                    TenantId TEXT NOT NULL,
                    ClientId TEXT NOT NULL,
                    CertificateThumbprint TEXT NOT NULL,
                    CertificateStoreName TEXT NOT NULL CHECK (CertificateStoreName = 'My'),
                    CertificateStoreLocation TEXT NOT NULL CHECK (CertificateStoreLocation IN ('LocalMachine', 'CurrentUser'))
                );
                INSERT INTO MicrosoftIdentityConfiguration
                    (Id, TenantId, ClientId, CertificateThumbprint, CertificateStoreName, CertificateStoreLocation)
                SELECT Id, TenantId, ClientId, CertificateThumbprint, CertificateStoreName, CertificateStoreLocation
                FROM MicrosoftIdentityConfiguration_M4;
                DROP TABLE MicrosoftIdentityConfiguration_M4;
                PRAGMA user_version = 3;
                """;
            command.ExecuteNonQuery();
        }

        var restarted = new RelayDatabase(
            new RelayStorageOptions { DataDirectory = context.Database.DataDirectory },
            AppContext.BaseDirectory);
        restarted.Initialize();

        Assert.Equal(active.ClientId, restarted.GetMicrosoftIdentityConfiguration()!.ClientId);
        Assert.Null(restarted.GetMicrosoftAuthorizedSender());
        Assert.Null(restarted.GetMicrosoftSetupState());
        using var verification = restarted.OpenConnectionForDiagnostics();
        using var version = verification.CreateCommand();
        version.CommandText = "PRAGMA user_version;";
        Assert.Equal(9L, (long)version.ExecuteScalar()!);
    }

    private static MicrosoftSetupState ReadyState()
    {
        return new MicrosoftSetupState(
            MicrosoftSetupStep.ExchangePermission,
            MicrosoftSetupMode.ExistingApplication,
            MicrosoftCertificateReference.Create(
                "0123456789ABCDEF0123456789ABCDEF01234567",
                CertificateStoreTarget.LocalMachine),
            Guid.Parse("10000000-0000-0000-0000-000000000001"),
            Guid.Parse("20000000-0000-0000-0000-000000000002"),
            Guid.Parse("30000000-0000-0000-0000-000000000003"),
            "scanner@example.com",
            true,
            true,
            false,
            false,
            false,
            DateTimeOffset.Parse("2026-08-22T10:00:00Z"),
            Guid.Parse("40000000-0000-0000-0000-000000000004"));
    }

    private static MicrosoftSetupState CompletedState(
        SetupTestContext context,
        MicrosoftIdentityConfiguration configuration,
        Guid servicePrincipalObjectId)
    {
        return new MicrosoftSetupState(
            MicrosoftSetupStep.Complete,
            MicrosoftSetupMode.NewApplication,
            context.Certificate,
            configuration.TenantId,
            configuration.ClientId,
            servicePrincipalObjectId,
            "scanner@example.com",
            EntraResultValidated: true,
            ExchangeResultValidated: true,
            IdentityValidated: true,
            ExchangeValidated: true,
            TestMessageAccepted: true,
            DateTimeOffset.UtcNow,
            Guid.NewGuid(),
            Revision: 1,
            Lifecycle: MicrosoftSetupCandidateLifecycle.Activated);
    }

    private static JsonDocument DecodeScriptPayload(string script)
    {
        const string marker = "FromBase64String('";
        var start = script.IndexOf(marker, StringComparison.Ordinal);
        Assert.True(start >= 0);
        start += marker.Length;
        var end = script.IndexOf("')", start, StringComparison.Ordinal);
        Assert.True(end > start);
        var json = Encoding.UTF8.GetString(Convert.FromBase64String(script[start..end]));
        return JsonDocument.Parse(json);
    }

    private static void PrepareCandidate(SetupTestContext context, Guid tenantId, Guid clientId)
    {
        context.Setup.Begin(MicrosoftSetupMode.NewApplication);
        context.Setup.SelectCertificate(context.Certificate);
        context.Setup.ApplyEntraResult(
            $$"""{"TenantId":"{{tenantId:D}}","ClientId":"{{clientId:D}}","ServicePrincipalObjectId":"{{Guid.NewGuid():D}}","ApiPermissionEntryCount":0}""");
        context.Setup.SetSenderMailbox("scanner@example.com");
        context.Setup.ApplyExchangeResult(
            """{"ServicePrincipalConfigured":true,"ScopeConfigured":true,"Role":"Application SMTP.SendAsApp","SenderInScope":true}""");
    }

    private static void PrepareNativeCandidateStart(SetupTestContext context)
    {
        context.Setup.Begin(MicrosoftSetupMode.NewApplication);
        context.Setup.SelectCertificate(context.Certificate);
        context.Setup.SetSenderMailbox("scanner@example.com");
    }

    private static ExchangeSetupResult ValidExchangeResult() => new(
        true,
        true,
        "Application SMTP.SendAsApp",
        true);

    private static NativeMicrosoftCandidateIdentity PrepareNativeValidatedCandidate(SetupTestContext context)
    {
        PrepareNativeCandidateStart(context);
        var candidate = context.Setup.CaptureNativeCandidate();
        candidate = context.Setup.ApplyNativeEntraResult(
            candidate,
            new EntraSetupResult(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), 0));
        return context.Setup.ApplyNativeExchangeResult(candidate, ValidExchangeResult());
    }

    private static QueueLifecycleHarness CreateQueueLifecycle(
        SetupTestContext context,
        bool enabled,
        IMailDeliveryProvider provider)
    {
        var options = new QueueOptions
        {
            Enabled = enabled,
            MaxConcurrency = 1,
            PollInterval = TimeSpan.FromMilliseconds(100),
            MinimumFreeDiskBytes = 0,
        };
        var fileSystem = new PhysicalSpoolFileSystem();
        var signal = new QueueWorkSignal();
        var capacity = new QueueCapacityManager(context.Database, fileSystem, options);
        var store = new DurableMessageStore(context.Database, fileSystem, capacity, signal);
        var worker = new QueueWorker(
            context.Database,
            fileSystem,
            provider,
            options,
            signal,
            context.QueueDeliveryActivation,
            TimeProvider.System,
            NullLogger<QueueWorker>.Instance);
        var reconciler = new QueueReconciler(
            context.Database,
            fileSystem,
            options,
            TimeProvider.System,
            NullLogger<QueueReconciler>.Instance);
        var hostedService = new QueueHostedService(
            reconciler,
            worker,
            signal,
            context.QueueDeliveryActivation,
            context.Database,
            context.Certificates,
            options,
            NullLogger<QueueHostedService>.Instance);
        var device = new DeviceService(context.Database).AddLegacyDevice(
            $"Queue activation {Guid.NewGuid():N}",
            ["127.0.0.1"],
            ["scanner@example.com"]);
        return new QueueLifecycleHarness(hostedService, worker, store, device.Id);
    }

    private static async Task<QueuedMessage> EnqueueAsync(QueueLifecycleHarness queue)
    {
        const int size = 64;
        await using var receive = queue.Store.BeginReceive(size);
        await receive.Stream.WriteAsync(new byte[size]);
        return await receive.CommitAsync(
            queue.DeviceId,
            "scanner@example.com",
            ["recipient@example.net"],
            size,
            CancellationToken.None);
    }

    private static async Task WaitUntilAsync(Func<bool> condition, TimeSpan timeout)
    {
        using var deadline = new CancellationTokenSource(timeout);
        while (!condition())
        {
            await Task.Delay(20, deadline.Token);
        }
    }

    private sealed record QueueLifecycleHarness(
        QueueHostedService HostedService,
        QueueWorker Worker,
        DurableMessageStore Store,
        Guid DeviceId);

    private sealed class SetupTestContext : IAsyncDisposable
    {
        private readonly string _dataDirectory;
        private readonly MicrosoftTokenProvider _tokens;

        private SetupTestContext(
            string dataDirectory,
            RelayDatabase database,
            MicrosoftCertificateService certificates,
            MicrosoftCertificateReference certificate,
            FakeIdentityFactory identityFactory,
            MicrosoftTokenProvider tokens,
            FakeExchangeSmtpServer server,
            MicrosoftIdentityRuntimeState identityRuntime,
            ExchangeDeliveryRuntimeState exchangeRuntime,
            ExchangeDeliveryTester exchangeTester,
            QueueDeliveryActivation queueDeliveryActivation,
            MicrosoftSetupService setup)
        {
            _dataDirectory = dataDirectory;
            Database = database;
            Certificates = certificates;
            Certificate = certificate;
            IdentityFactory = identityFactory;
            _tokens = tokens;
            Server = server;
            IdentityRuntime = identityRuntime;
            ExchangeRuntime = exchangeRuntime;
            ExchangeTester = exchangeTester;
            QueueDeliveryActivation = queueDeliveryActivation;
            Setup = setup;
        }

        public RelayDatabase Database { get; }
        public MicrosoftCertificateService Certificates { get; }
        public MicrosoftCertificateReference Certificate { get; }
        public FakeIdentityFactory IdentityFactory { get; }
        public FakeExchangeSmtpServer Server { get; }
        public MicrosoftIdentityRuntimeState IdentityRuntime { get; }
        public ExchangeDeliveryRuntimeState ExchangeRuntime { get; }
        public ExchangeDeliveryTester ExchangeTester { get; }
        public QueueDeliveryActivation QueueDeliveryActivation { get; }
        public MicrosoftSetupService Setup { get; }

        public static Task<SetupTestContext> CreateAsync(
            FakeExchangeScenario? scenario = null,
            MicrosoftSetupPersistenceHooks? persistenceHooks = null,
            IReadOnlyList<TimeSpan>? smtpPropagationRetryDelays = null)
        {
            var directory = Path.Combine(Path.GetTempPath(), "RelayBridge.SetupTests", Guid.NewGuid().ToString("N"));
            var database = new RelayDatabase(
                new RelayStorageOptions { DataDirectory = directory },
                AppContext.BaseDirectory);
            database.Initialize();
            var identityOptions = new MicrosoftIdentityOptions();
            var certificates = new MicrosoftCertificateService(database, identityOptions, TimeProvider.System);
            var metadata = certificates.GenerateSelfSignedCertificate(CertificateStoreTarget.CurrentUser);
            var reference = MicrosoftCertificateReference.Create(
                metadata.Thumbprint,
                CertificateStoreTarget.CurrentUser);
            var identityFactory = new FakeIdentityFactory();
            var tokens = new MicrosoftTokenProvider(database, certificates, identityFactory);
            var server = new FakeExchangeSmtpServer(scenario ?? new FakeExchangeScenario());
            server.Start();
            var sequence = new MicrosoftRuntimeEvidenceSequence();
            var identityRuntime = new MicrosoftIdentityRuntimeState(database, sequence);
            var identityTester = new MicrosoftAuthenticationTester(
                database,
                certificates,
                tokens,
                identityRuntime,
                TimeProvider.System,
                new TestLogger<MicrosoftAuthenticationTester>());
            var runtime = new ExchangeDeliveryRuntimeState(sequence);
            var options = new ExchangeSmtpOptions
            {
                ConnectTimeout = TimeSpan.FromSeconds(5),
                TlsTimeout = TimeSpan.FromSeconds(5),
                CommandTimeout = TimeSpan.FromSeconds(5),
                DataTerminationTimeout = TimeSpan.FromSeconds(5),
                MinimumDataTimeout = TimeSpan.FromSeconds(10),
                DataTimeoutPerMiB = TimeSpan.FromSeconds(2),
                MaximumDataTimeout = TimeSpan.FromMinutes(2),
                ConfigurationFailureRetryAfter = TimeSpan.FromMinutes(5),
            };
            var provider = new ExchangeSmtpOAuthProvider(
                tokens,
                options,
                server.CreateEndpoint(trustTestCertificate: true),
                runtime,
                TimeProvider.System,
                new TestLogger<ExchangeSmtpOAuthProvider>());
            var tester = new ExchangeDeliveryTester(provider, runtime, TimeProvider.System);
            var queueDeliveryActivation = new QueueDeliveryActivation();
            var setup = new MicrosoftSetupService(
                database,
                certificates,
                tokens,
                identityTester,
                tester,
                queueDeliveryActivation,
                TimeProvider.System,
                persistenceHooks,
                smtpPropagationRetryDelays ??
                    [TimeSpan.FromMilliseconds(1), TimeSpan.FromMilliseconds(1), TimeSpan.FromMilliseconds(1)]);
            return Task.FromResult(new SetupTestContext(
                directory,
                database,
                certificates,
                reference,
                identityFactory,
                tokens,
                server,
                identityRuntime,
                runtime,
                tester,
                queueDeliveryActivation,
                setup));
        }

        public MicrosoftSetupService CreateSetupService(MicrosoftSetupPersistenceHooks? persistenceHooks = null) => new(
            Database,
            Certificates,
            _tokens,
            new MicrosoftAuthenticationTester(
                Database,
                Certificates,
                _tokens,
                IdentityRuntime,
                TimeProvider.System,
                new TestLogger<MicrosoftAuthenticationTester>()),
            ExchangeTester,
            QueueDeliveryActivation,
            TimeProvider.System,
            persistenceHooks);

        public async ValueTask DisposeAsync()
        {
            await Server.DisposeAsync();
            _tokens.Dispose();
            RemoveCertificateAndKey(Certificate);
            Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();
            if (Directory.Exists(_dataDirectory))
            {
                Directory.Delete(_dataDirectory, recursive: true);
            }
        }

        private static void RemoveCertificateAndKey(MicrosoftCertificateReference reference)
        {
            using var store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
            store.Open(OpenFlags.ReadWrite);
            var matches = store.Certificates.Find(
                X509FindType.FindByThumbprint,
                reference.Thumbprint,
                validOnly: false);
            foreach (var certificate in matches.Cast<X509Certificate2>())
            {
                string? keyName = null;
                using (var rsa = certificate.GetRSAPrivateKey())
                {
                    if (rsa is RSACng cng)
                    {
                        keyName = cng.Key.KeyName;
                    }
                }

                store.Remove(certificate);
                certificate.Dispose();
                if (keyName is not null && CngKey.Exists(keyName, CngProvider.MicrosoftSoftwareKeyStorageProvider))
                {
                    using var key = CngKey.Open(keyName, CngProvider.MicrosoftSoftwareKeyStorageProvider);
                    key.Delete();
                }
            }
        }
    }

    private sealed class FakeIdentityFactory : IMicrosoftIdentityClientFactory
    {
        public MicrosoftIdentityException? Error { get; set; }
        public MicrosoftIdentityConfiguration? LastConfiguration { get; private set; }

        public IMicrosoftIdentityClient Create(
            MicrosoftIdentityConfiguration configuration,
            X509Certificate2 certificate)
        {
            LastConfiguration = configuration;
            return new FakeIdentityClient(this, configuration.TenantId);
        }

        private sealed class FakeIdentityClient : IMicrosoftIdentityClient
        {
            private readonly FakeIdentityFactory _owner;
            private readonly Guid _tenantId;

            public FakeIdentityClient(FakeIdentityFactory owner, Guid tenantId)
            {
                _owner = owner;
                _tenantId = tenantId;
            }

            public Task<MicrosoftAccessToken> AcquireTokenAsync(
                string scope,
                CancellationToken cancellationToken)
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (_owner.Error is not null)
                {
                    throw _owner.Error;
                }

                return Task.FromResult(new MicrosoftAccessToken(
                    "fake-m5-token",
                    DateTimeOffset.UtcNow.AddMinutes(30),
                    _tenantId));
            }
        }
    }
}
